### ISSUE TITLE
Can you update to latest framework7 1.3.1

### ISSUE THREAD

**Issue by niravanu** [nobutakaoshiro/meteor-framework7-ios-material#4]
Can you update to latest framework7 1.3.1

https://github.com/nolimits4web/Framework7/blob/master/CHANGELOG.md

**Comment by notakaos** [comment]
@niravanu Thank you for your information of framework7!
I will try to update to latest framework7 1.3.1 in a few days.

**Comment by niravanu** [comment]
Great! Thanks!!

**Comment by sqndr** [comment]
Is there any way you can manually update to the latest version?
